<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Clinician[
<!ELEMENT Clinician (name,surname, email, phone)>
	<!ATTLIST Clinician speciality CDATA #REQUIRED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT surname (#PCDATA)>
	<!ELEMENT email (#PCDATA)>
	<!ELEMENT phone (#PCDATA)>
]>


<Clinician speciality="Trauma">
	<name>Gregory</name>
	<surname>Dorwin</surname>
	<email>dorwin@mail.com</email>
	<phone>6895205</phone>	
</Clinician>